### ISSUE TITLE
binary_card_sensor_alert and card_battery not functionaing correctly against latest minimalist versions

### ISSUE THREAD

**Issue by ant71** [EverythingSmartHome/ui-minimalist-guide#3]
The lines in bathroom.yaml giving friendly names and setting the show_last_changed value do not work with latest version of these cards (v1.0.2 of UI-Lovelace-Minimalist/UI) . The following slight syntax change renders correctly against the latest versions

```
- type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        template: card_binary_sensor_alert
        variables:
          ulm_card_binary_sensor_alert: true
          ulm_show_last_changed: true
          ulm_card_binary_sensor_alert_name: Presence
        entity: binary_sensor.aqara_fp1_presence
      - type: 'custom:button-card'
        template: card_battery
        entity: sensor.livingroom_trv_battery
        variables:
            ulm_card_battery_battery_level_danger: 20
            ulm_card_battery_battery_level_warning: 50
            ulm_card_battery_name: TRV
```

Great introduction to Minimalist. Thank you!
